spring.application.name=rescue

# Incident PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/rescue_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Apache Kafka Consumer Configuration
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=rescue-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Key & Value Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Modern ErrorHandlingDeserializer Delegate Settings
spring.kafka.consumer.properties.spring.json.value.default.type=com.dms.common.events.IncidentCreatedEvent
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Package Trust Strategy for JSON Deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.dms.*

# Topic Property
application.kafka.topic.incident-created=incident-created-topic