spring.application.name=incident
server.port=8082

# Incident PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Must match the secret key in user-service exactly!
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# ==========================================
# Apache Kafka General & Producer Configuration
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092

# Serializers for Key (String) and Value (JSON)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Custom Topic Properties
application.kafka.topic.incident-created=incident-created-topic
app.kafka.topics.rescue-mission-status=rescue-mission-status-topic

# ==========================================
# Apache Kafka Consumer Configuration
# ==========================================
spring.kafka.consumer.group-id=incident-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Consumer Deserializers using ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON Deserializer Trusted Packages & Defaults
spring.kafka.properties.spring.json.trusted.packages=*
spring.kafka.properties.spring.json.value.default.type=com.dms.common.events.RescueMissionStatusUpdatedEvent
spring.kafka.properties.spring.json.use.type.info.headers=false